### ISSUE TITLE
Flakey CI runs in test_local_docker

### ISSUE THREAD

**Issue by adborden** [GSA/ckanext-dcat_usmetadata#104]
For a readme change, test_local_docker failed twice with different errors.

- https://app.circleci.com/pipelines/github/GSA/ckanext-dcat_usmetadata/408/workflows/5fd8447c-8dbe-4b24-bd01-9dfe35d6583c/jobs/934
- https://app.circleci.com/pipelines/github/GSA/ckanext-dcat_usmetadata/408/workflows/110f0f00-7b47-4e2f-9dae-bb6bd4b457ae/jobs/950

Retrying a third time succeeded.

**Comment by kmanaseryan** [comment]
@adborden I think this we have some success on this already. After PR #105 related to encodings I haven't experienced this any more. There are some other places that we explicitly wait for some seconds, those are also potential breaking points, but so far so good after the recent PR. Of course we can improve this to make CI smoother. 

I remember you have [noted](https://github.com/GSA/ckanext-dcat_usmetadata/issues/97#issuecomment-706453173) this earlier
