### ISSUE TITLE
Pre-select org when user is only a member of one

### ISSUE THREAD

**Issue by kimwdavidson** [GSA/ckanext-dcat_usmetadata#146]
## User story
As a data publisher, when I am only a member of one organization and I go to publish a dataset, that organization should be pre-selected in the dropdown, so that I can save time

## Acceptance Critiera
- When I am logged in as gsa-editor
- And I add a dataset
- And I scroll down to the organization dropdown
- Then I see the GSA organization as the only organization and it is already selected

**Comment by hkdctol** [comment]
This has been done.
<img width="1440" alt="inventory screenshot" src="https://user-images.githubusercontent.com/3236989/100677292-b99a1480-3338-11eb-855c-604830b4400f.png">
