### ISSUE TITLE
Linting is not running in CI

### ISSUE THREAD

**Issue by adborden** [GSA/ckanext-dcat_usmetadata#86]
Makefile describes linting tests for python and JS. Neither are running in CI.

- make lint-all
- make app-lint

**Comment by kmanaseryan** [comment]
@adborden I think this already done in #88

**Comment by adborden** [comment]
Chatted about this in our backlog grooming session, we still need to add the python linting to CI.

**Comment by woodt** [comment]
It appears that the CircleCI pipeline is now running both JS and Python linters.  So technically, this story is done.

I do want to point out that the Python linter (flake8) is configured to only look at the "E9*" series of errors, which I believe include *only*:

E9	Runtime
E901	SyntaxError or IndentationError
E902	IOError

So, better than nothing, but not too much.

**Comment by avdata99** [comment]
In catalog-next we are linting just `E9`: https://github.com/GSA/catalog.data.gov/blob/master/Makefile#L62
Python linting is running CI: https://github.com/GSA/ckanext-dcat_usmetadata/blob/master/.circleci/config.yml#L41:L41
JS linting is also running in CI: https://github.com/GSA/ckanext-dcat_usmetadata/blob/master/.circleci/config.yml#L23:L23

I agree with @woodt. This is done 
Note: The `makefile` no longer exists. 

cc: @anuveyatsu @adborden

**Comment by adborden** [comment]
@anuveyatsu when I run `yarn lint:python` I see this error in the output, but the command keeps running.
> /bin/sh: CKAN_HOME: command not found

This makes it seem like linting is not working. If I remove `--select E9` to run all flake8 checks, I get 77,105 errors, including errors in external dependencies, which is incorrect:
```
# ...
./.local/share/virtualenv/wheel/2.7/image/1/CopyPipInstall/setuptools-44.1.1-py2.py3-none-any/setuptools/_vendor/packaging/version.py:418:80: E501 line too long (87 > 79 characters)
        local = tuple((i, "") if isinstance(i, int) else (-Infinity, i) for i in local)
                                                                               ^
6     E111 indentation is not a multiple of four
16    E114 indentation is not a multiple of four (comment)
12    E115 expected an indented block (comment)
73    E116 unexpected indentation (comment)
10324 E122 continuation line missing indentation or outdented
2     E124 closing bracket does not match visual indentation
1     E125 continuation line with same indent as next logical line
77    E127 continuation line over-indented for visual indent
123   E128 continuation line under-indented for visual indent
19    E129 visually indented line with same indent as next logical line
253   E131 continuation line unaligned for hanging indent
959   E201 whitespace after '{'
980   E202 whitespace before '}'
43    E203 whitespace before ','
5     E211 whitespace before '('
133   E221 multiple spaces before operator
61    E225 missing whitespace around operator
4     E227 missing whitespace around bitwise or shift operator
56613 E231 missing whitespace after ','
36    E251 unexpected spaces around keyword / parameter equals
770   E261 at least two spaces before inline comment
205   E262 inline comment should start with '# '
190   E265 block comment should start with '# '
91    E266 too many leading '#' for block comment
3     E271 multiple spaces after keyword
4     E272 multiple spaces before keyword
60    E301 expected 1 blank line, found 0
414   E302 expected 2 blank lines, found 1
27    E303 too many blank lines (3)
78    E305 expected 2 blank lines after class or function definition, found 1
26    E306 expected 1 blank line before a nested definition, found 0
1     E401 multiple imports on one line
27    E402 module level import not at top of file
4733  E501 line too long (80 > 79 characters)
5     E502 the backslash is redundant between brackets
11    E701 multiple statements on one line (colon)
4     E713 test for membership should be 'not in'
1     E714 test for object identity should be 'is not'
10    E722 do not use bare 'except'
20    E731 do not assign a lambda expression, use a def
57    E741 ambiguous variable name 'l'
145   F401 'ctypes.windll' imported but unused
4     F403 'from .core import *' used; unable to detect undefined names
2     F405 'encode' may be undefined, or defined from star imports: .codec, .core
1     F523 '...'.format(...) has unused arguments at position(s): 2
3     F811 redefinition of unused 're' from line 10
2     F812 list comprehension redefines 'arch' from line 34
12    F821 undefined name 'get_ident'
29    F841 local variable 'success' is assigned to but never used
160   W291 trailing whitespace
259   W293 blank line contains whitespace
11    W391 blank line at end of file
77105
error Command failed with exit code 1.
```


I agree with @woodt, that only running the E9 checks are not enough. I'd like to see how much work this is to get working with all of flake8's default checks (some exceptions are okay). If it's too large we will split it into it's own story.

**Comment by anuveyatsu** [comment]
@adborden I can reproduce the error you're having. Unfortunately it is somewhere in the beginning of the logs so it was easy to miss since the command completes with success message. We should be able to easily fix this.

Re linting level, we should be able to fix it within this issue as well because it looks quite straightforward to do it.

I will create a PR for this.
