### ISSUE TITLE
Metadata inventory form does not handle `&`

### ISSUE THREAD

**Issue by adborden** [GSA/ckanext-dcat_usmetadata#97]
Attempting to enter the [Per Diem Reimbursement Rates & API](https://catalog.data.gov/dataset/fy2013-per-diem-reimbursement-rates) dataset, I noticed that the `&` is not handled correctly and truncates/splits the JSON payload into two parameters. CKAN sees the truncated payload and 400's because it's not complete JSON.

## How to reproduce
1. https://inventory.sandbox.datagov.us/dataset/new-metadata
1. Enter a title, including an `&`, e.g. "Per Diem Reimbursement Rates & API"
1. Fill out the form as usual
1. Click "Save and Continue"

## Expected

Dataset is saved and the form moves to the Additional metadata form.

## Actual

400 with the message:

> Error saving metadata
> Something has failed. Please, try again later or contact site administrator.

**Comment by adborden** [comment]
I think this is a side-effect of our work-around for https://github.com/GSA/datagov-deploy/issues/1177. I'm pretty sure we can just `encodeURIComponent` the payload.

**Comment by adborden** [comment]
I think this is also why the integration tests are flakey. `chance.string` is used for the form input to [unique_id](https://github.com/GSA/ckanext-dcat_usmetadata/blob/8fd519cc5d142a3ba7a5ee4e0c08c5572b009479/cypress/support/commands.js#L33), which includes `&` in the random sample set.

**Comment by adborden** [comment]
I'm not seeing tests included with https://github.com/GSA/ckanext-dcat_usmetadata/issues/99. Just a reminder that as part of our [Definition of Done](https://github.com/GSA/datagov-ckan-multi/blob/master/CONTRIBUTING.md#exit-criteria-7), tests are included and running in CI. I'm moving this back to To Do.

**Comment by adborden** [comment]
Verified on sandbox.

**Comment by adborden** [comment]
Was doing a little more testing and while we get through the first page, we don't make it through the second page (Additional Metadata). It looks like the same issue, the request body is truncated at `&`.

**Comment by kmanaseryan** [comment]
@adborden can you provide the steps how to reproduce? Any field from the payload is being [encoded](https://github.com/GSA/ckanext-dcat_usmetadata/blob/master/metadata-app/src/api/index.js#L28) including extras, and property names. 

We have also Jest test written which checks the encodings. I see in the test we check some fields from first page, but we also have a random property name test. Additionally I just checked this manually with all text fields having speciall chars. The dataset has been saved successfully.

**Comment by adborden** [comment]
@kmanaseryan the repro is the same, just click "save and continue" from the additional metadata page.

1. https://inventory.sandbox.datagov.us/dataset/new-metadata
1. Enter a title, including an `&`, e.g. "Per Diem Reimbursement Rates & API"
1. Fill out the form as usual
1. Click "Save and Continue"
1. On the Additional Metadata page, click "Save and Continue"

**Comment by adborden** [comment]
It looks like it's the `notes` field is what's failing. Here's the response:
```
"Bad request - JSON Error: Error decoding JSON data. Error: JSONDecodeError('Unterminated string starting at: line 1 column 1066 (char 1065)',) JSON data extracted from the request: '{\"license_title\":null,\"maintainer\":null,\"relationships_as_object\":[],\"private\":false,\"maintainer_email\":null,\"num_tags\":1,\"id\":\"cadadf58-61cc-4f6e-9197-00a6a7eaa80a\",\"metadata_created\":\"2020-10-22T18:35:03.497652\",\"metadata_modified\":\"2020-10-22T18:35:03.526081\",\"author\":null,\"author_email\":null,\"state\":\"draft\",\"version\":null,\"creator_user_id\":\"0b605f4d-22e6-410c-b6b2-21f7e1823508\",\"type\":\"dataset\",\"resources\":[],\"num_resources\":0,\"tags\":[{\"vocabulary_id\":null,\"state\":\"active\",\"display_name\":\"asdf\",\"id\":\"1aa722ba-f559-4bef-8a3a-b953f0616816\",\"name\":\"asdf\"}],\"groups\":[],\"license_id\":null,\"relationships_as_subject\":[],\"organization\":{\"description\":\"\",\"created\":\"2020-09-24T22:32:36.478258\",\"title\":\"General Services Administration\",\"name\":\"general-services-administration\",\"is_organization\":true,\"state\":\"active\",\"image_url\":\"\",\"revision_id\":\"8535b66a-095e-445c-bd05-fabc7a7f1973\",\"type\":\"organization\",\"id\":\"b4d721be-d175-4610-958d-c56cd94cbeac\",\"approval_status\":\"approved\"},\"name\":\"per-diem-reimbursement-rates-and-api-3\",\"isopen\":false,\"url\":null,\"notes\":\"Per Diem Reimbursement Rates '"
```
