### ISSUE TITLE
New metadata form does not load on IE11

### ISSUE THREAD

**Issue by osahon-okungbowa** [GSA/ckanext-dcat_usmetadata#98]
Visiting the new metadata form (https://inventory.sandbox.datagov.us/dataset/new-metadata) on IE 11 as a logged-in user, produces a blank page because a fatal error is raised when the form is loaded

![2020-10-11.png](https://images.zenhubusercontent.com/5e9c632e861fca84ed741203/653fd1e5-fbd8-4fb6-a4e3-27158e861399)

### Steps to Reproduce

1.  log in to the inventory sandbox https://inventory.sandbox.datagov.us
2.  visit the new metadata form https://inventory.sandbox.datagov.us/dataset/new-metadata

### Expected Behaviour

- the new metadata form is loaded and users can see/use the form inputs to create a new dataset

### Actual Behaviour

- a blank page is displayed due to a fatal error

## NOTES
-  from the error in the developer console, the metadata form uses the es6 Promise object which is NOT natively supported in IE11. An appropriate polyfil should be used to provide support for any es6 features used by the metadata form

**Comment by adborden** [comment]
FYI, anyone familiar with running VMs should be able to download a [free image from Microsoft](https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/) in order to reproduce. They have all versions of IE going back to IE8.

**Comment by hkdctol** [comment]
I confirmed through QA of the other ticket that the new metadata form does load on IE11.
